### ISSUE TITLE
Builds for macOS Ventura

### ISSUE THREAD

**Issue by domrim** [indigo-dc/homebrew-oidc-agent#22]
It would be nice if there are bottles for macOS 13 (Ventura). Could you add them to the Formula?

**Comment by zachmann** [comment]
We build bottles through github actions and github actions currently only supports runners on macos 11 and 12

**Comment by zachmann** [comment]
macos 13 runners are now available; the 4.5.2 release available in a few minutes will include bottles for macOS 13
